name: runtour
type:
  - masthead
activate: true

icon: fa-play
tooltip: 'runtour'

function: >
  $.getJSON("/api/webhooks/", function( data ) {
      for( var item in data ) {
          var webhook = data[item];
          if( webhook.name === "runtour" ) {
              if( webhook.script && !window.static_search ) {
                  $( '<script/>', { type: 'text/javascript' } ).text( webhook.script ).appendTo( 'head' );
                  $( '<style/>', { type: 'text/css' } ).text( webhook.styles ).appendTo( 'head' );    
              }
              break;
          }
      }
  });